function varargout = PsychLVGL(varargin) %#ok<STOUT,INUSD>
% PSYCHLVGL  LVGL 9 retained mode GUI panels for Psychtoolbox.
%
%   This file holds the help text. The compiled MEX in dist/<arch> shadows it.
%   If you see this error, the MEX is not built or not on the path.
%
%   Lifecycle and hand written subcommands:
%     glTex = PsychLVGL('Init', w, h [, opts])
%     PsychLVGL('Shutdown')
%     dirty = PsychLVGL('Update', tNow, mouse, wheel, keys)
%     E = PsychLVGL('Poll')
%     v = PsychLVGL('Version')
%     op = PsychLVGL('Opcode', name)
%     s = PsychLVGL('Stats' [, 'reset'])
%     PsychLVGL('StatsAddFrame', dt)
%     v = PsychLVGL('Enum', 'LV_EVENT_CLICKED')
%     names = PsychLVGL('FontList')
%     PsychLVGL('Log', level)
%     h = PsychLVGL('ScreenActive')
%     h = PsychLVGL('ScreenCreate')
%     PsychLVGL('ScreenLoad', h)
%     PsychLVGL('ObjDelete', h)
%     tf = PsychLVGL('IsValid', h)
%     PsychLVGL('AddEvent', h, 'LONG_PRESSED')
%     PsychLVGL('RemoveEvent', h, 'LONG_PRESSED')
%     PsychLVGL('AddToGroup', h)
%     PsychLVGL('RemoveFromGroup', h)
%     PsychLVGL('FocusObj', h)
%     name = PsychLVGL('EventName', code)
%     crc = PsychLVGL('FrameChecksum')
%     style = PsychLVGL('StyleCreate')
%     PsychLVGL('StyleDelete', style)
%     PsychLVGL('StyleSetProp', style, 'bg_color', value)
%     PsychLVGL('ObjAddStyle', h, style [, selector])
%     PsychLVGL('ObjRemoveStyle', h, style [, selector])
%     PsychLVGL('ObjRemoveStyleAll', h)
%     img = PsychLVGL('ImageFromTexture', glTex, w, h [, transposed])
%     img = PsychLVGL('ImageFromArray', uint8Image)
%     PsychLVGL('ImageDelete', img)
%     font = PsychLVGL('FontLoad', ttfPath, px)
%     PsychLVGL('FontDelete', font)
%     PsychLVGL('ChartSetValues', chart, series, values)
%     values = PsychLVGL('ChartGetValues', chart, series)
%
%   Generated subcommands (one per allowlisted LVGL function):
%     ret = PsychLVGL('ArcCreate', parent)
%     ret = PsychLVGL('ArcGetValue', obj)
%     PsychLVGL('ArcSetAngles', obj, start, end)
%     PsychLVGL('ArcSetBgAngles', obj, start, end)
%     PsychLVGL('ArcSetMode', obj, type)
%     PsychLVGL('ArcSetRange', obj, min, max)
%     PsychLVGL('ArcSetRotation', obj, rotation)
%     PsychLVGL('ArcSetValue', obj, value)
%     ret = PsychLVGL('BarCreate', parent)
%     ret = PsychLVGL('BarGetValue', obj)
%     PsychLVGL('BarSetMode', obj, mode)
%     PsychLVGL('BarSetRange', obj, min, max)
%     PsychLVGL('BarSetStartValue', obj, start_value, anim)
%     PsychLVGL('BarSetValue', obj, value, anim)
%     ret = PsychLVGL('ButtonCreate', parent)
%     ret = PsychLVGL('ChartAddCursor', obj, color, dir)
%     ret = PsychLVGL('ChartAddSeries', obj, color, axis)
%     ret = PsychLVGL('ChartCreate', parent)
%     ret = PsychLVGL('ChartGetPointCount', obj)
%     ret = PsychLVGL('ChartGetPressedPoint', obj)
%     ret = PsychLVGL('ChartGetSeriesColor', chart, series)
%     ret = PsychLVGL('ChartGetType', obj)
%     ret = PsychLVGL('ChartGetUpdateMode', obj)
%     ret = PsychLVGL('ChartGetXStartPoint', obj, ser)
%     PsychLVGL('ChartHideSeries', chart, series, hide)
%     PsychLVGL('ChartRefresh', obj)
%     PsychLVGL('ChartRemoveCursor', obj, cursor)
%     PsychLVGL('ChartRemoveSeries', obj, series)
%     PsychLVGL('ChartSetAllValues', obj, ser, value)
%     PsychLVGL('ChartSetAxisMaxValue', obj, axis, max)
%     PsychLVGL('ChartSetAxisMinValue', obj, axis, min)
%     PsychLVGL('ChartSetAxisRange', obj, axis, min, max)
%     PsychLVGL('ChartSetCursorPoint', chart, cursor, ser, point_id)
%     PsychLVGL('ChartSetCursorPosX', chart, cursor, x)
%     PsychLVGL('ChartSetCursorPosY', chart, cursor, y)
%     PsychLVGL('ChartSetDivLineCount', obj, hdiv, vdiv)
%     PsychLVGL('ChartSetNextValue', obj, ser, value)
%     PsychLVGL('ChartSetPointCount', obj, cnt)
%     PsychLVGL('ChartSetSeriesColor', chart, series, color)
%     PsychLVGL('ChartSetSeriesValueById', obj, ser, id, value)
%     PsychLVGL('ChartSetSeriesValues', obj, ser, values)
%     PsychLVGL('ChartSetType', obj, type)
%     PsychLVGL('ChartSetUpdateMode', obj, update_mode)
%     PsychLVGL('ChartSetXStartPoint', obj, ser, id)
%     ret = PsychLVGL('CheckboxCreate', parent)
%     ret = PsychLVGL('CheckboxGetText', obj)
%     PsychLVGL('CheckboxSetText', obj, txt)
%     PsychLVGL('DropdownAddOption', obj, option, pos)
%     PsychLVGL('DropdownClearOptions', obj)
%     PsychLVGL('DropdownClose', obj)
%     ret = PsychLVGL('DropdownCreate', parent)
%     ret = PsychLVGL('DropdownGetSelected', obj)
%     buf = PsychLVGL('DropdownGetSelectedStr', obj)
%     PsychLVGL('DropdownOpen', dropdown_obj)
%     PsychLVGL('DropdownSetDir', obj, dir)
%     PsychLVGL('DropdownSetOptions', obj, options)
%     PsychLVGL('DropdownSetSelected', obj, sel_opt)
%     PsychLVGL('DropdownSetText', obj, text)
%     ret = PsychLVGL('ImageCreate', parent)
%     ret = PsychLVGL('ImageGetRotation', obj)
%     ret = PsychLVGL('ImageGetScale', obj)
%     ret = PsychLVGL('ImageGetSrcHeight', obj)
%     ret = PsychLVGL('ImageGetSrcWidth', obj)
%     PsychLVGL('ImageSetAntialias', obj, antialias)
%     PsychLVGL('ImageSetInnerAlign', obj, align)
%     PsychLVGL('ImageSetOffsetX', obj, x)
%     PsychLVGL('ImageSetOffsetY', obj, y)
%     PsychLVGL('ImageSetPivot', obj, x, y)
%     PsychLVGL('ImageSetRotation', obj, angle)
%     PsychLVGL('ImageSetScale', obj, zoom)
%     PsychLVGL('ImageSetScaleX', obj, zoom)
%     PsychLVGL('ImageSetScaleY', obj, zoom)
%     PsychLVGL('ImageSetSrc', obj, src)
%     ret = PsychLVGL('LabelCreate', parent)
%     ret = PsychLVGL('LabelGetText', obj)
%     PsychLVGL('LabelSetLongMode', obj, long_mode)
%     PsychLVGL('LabelSetText', obj, text)
%     PsychLVGL('ObjAddFlag', obj, f)
%     PsychLVGL('ObjAddState', obj, state)
%     PsychLVGL('ObjAlign', obj, align, x_ofs, y_ofs)
%     PsychLVGL('ObjAlignTo', obj, base, align, x_ofs, y_ofs)
%     PsychLVGL('ObjCenter', obj)
%     ret = PsychLVGL('ObjCreate', parent)
%     ret = PsychLVGL('ObjGetChild', obj, idx)
%     ret = PsychLVGL('ObjGetChildCount', obj)
%     ret = PsychLVGL('ObjGetHeight', obj)
%     ret = PsychLVGL('ObjGetParent', obj)
%     ret = PsychLVGL('ObjGetWidth', obj)
%     ret = PsychLVGL('ObjGetX', obj)
%     ret = PsychLVGL('ObjGetY', obj)
%     ret = PsychLVGL('ObjHasFlag', obj, f)
%     ret = PsychLVGL('ObjHasState', obj, state)
%     ret = PsychLVGL('ObjInvalidate', obj)
%     PsychLVGL('ObjRemoveFlag', obj, f)
%     PsychLVGL('ObjRemoveState', obj, state)
%     PsychLVGL('ObjScrollToView', obj, anim_en)
%     PsychLVGL('ObjSetFlexAlign', obj, main_place, cross_place, track_cross_place)
%     PsychLVGL('ObjSetFlexFlow', obj, flow)
%     PsychLVGL('ObjSetHeight', obj, h)
%     PsychLVGL('ObjSetLayout', obj, layout)
%     PsychLVGL('ObjSetParent', obj, parent)
%     PsychLVGL('ObjSetPos', obj, x, y)
%     PsychLVGL('ObjSetSize', obj, w, h)
%     PsychLVGL('ObjSetStyleAlign', obj, value, selector)
%     PsychLVGL('ObjSetStyleAnimDuration', obj, value, selector)
%     PsychLVGL('ObjSetStyleArcColor', obj, value, selector)
%     PsychLVGL('ObjSetStyleArcOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleArcRounded', obj, value, selector)
%     PsychLVGL('ObjSetStyleArcWidth', obj, value, selector)
%     PsychLVGL('ObjSetStyleBaseDir', obj, value, selector)
%     PsychLVGL('ObjSetStyleBgColor', obj, value, selector)
%     PsychLVGL('ObjSetStyleBgGradColor', obj, value, selector)
%     PsychLVGL('ObjSetStyleBgGradDir', obj, value, selector)
%     PsychLVGL('ObjSetStyleBgGradOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleBgGradStop', obj, value, selector)
%     PsychLVGL('ObjSetStyleBgImageOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleBgImageRecolor', obj, value, selector)
%     PsychLVGL('ObjSetStyleBgImageRecolorOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleBgImageTiled', obj, value, selector)
%     PsychLVGL('ObjSetStyleBgMainOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleBgMainStop', obj, value, selector)
%     PsychLVGL('ObjSetStyleBgOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleBlendMode', obj, value, selector)
%     PsychLVGL('ObjSetStyleBlurBackdrop', obj, value, selector)
%     PsychLVGL('ObjSetStyleBlurQuality', obj, value, selector)
%     PsychLVGL('ObjSetStyleBlurRadius', obj, value, selector)
%     PsychLVGL('ObjSetStyleBorderColor', obj, value, selector)
%     PsychLVGL('ObjSetStyleBorderOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleBorderPost', obj, value, selector)
%     PsychLVGL('ObjSetStyleBorderSide', obj, value, selector)
%     PsychLVGL('ObjSetStyleBorderWidth', obj, value, selector)
%     PsychLVGL('ObjSetStyleClipCorner', obj, value, selector)
%     PsychLVGL('ObjSetStyleColorFilterOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleDropShadowColor', obj, value, selector)
%     PsychLVGL('ObjSetStyleDropShadowOffsetX', obj, value, selector)
%     PsychLVGL('ObjSetStyleDropShadowOffsetY', obj, value, selector)
%     PsychLVGL('ObjSetStyleDropShadowOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleDropShadowQuality', obj, value, selector)
%     PsychLVGL('ObjSetStyleDropShadowRadius', obj, value, selector)
%     PsychLVGL('ObjSetStyleFlexCrossPlace', obj, value, selector)
%     PsychLVGL('ObjSetStyleFlexFlow', obj, value, selector)
%     PsychLVGL('ObjSetStyleFlexGrow', obj, value, selector)
%     PsychLVGL('ObjSetStyleFlexMainPlace', obj, value, selector)
%     PsychLVGL('ObjSetStyleFlexTrackPlace', obj, value, selector)
%     PsychLVGL('ObjSetStyleGridCellColumnPos', obj, value, selector)
%     PsychLVGL('ObjSetStyleGridCellColumnSpan', obj, value, selector)
%     PsychLVGL('ObjSetStyleGridCellRowPos', obj, value, selector)
%     PsychLVGL('ObjSetStyleGridCellRowSpan', obj, value, selector)
%     PsychLVGL('ObjSetStyleGridCellXAlign', obj, value, selector)
%     PsychLVGL('ObjSetStyleGridCellYAlign', obj, value, selector)
%     PsychLVGL('ObjSetStyleGridColumnAlign', obj, value, selector)
%     PsychLVGL('ObjSetStyleGridRowAlign', obj, value, selector)
%     PsychLVGL('ObjSetStyleHeight', obj, value, selector)
%     PsychLVGL('ObjSetStyleImageOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleImageRecolor', obj, value, selector)
%     PsychLVGL('ObjSetStyleImageRecolorOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleLayout', obj, value, selector)
%     PsychLVGL('ObjSetStyleLength', obj, value, selector)
%     PsychLVGL('ObjSetStyleLineColor', obj, value, selector)
%     PsychLVGL('ObjSetStyleLineDashGap', obj, value, selector)
%     PsychLVGL('ObjSetStyleLineDashWidth', obj, value, selector)
%     PsychLVGL('ObjSetStyleLineOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleLineRounded', obj, value, selector)
%     PsychLVGL('ObjSetStyleLineWidth', obj, value, selector)
%     PsychLVGL('ObjSetStyleMarginAll', obj, value, selector)
%     PsychLVGL('ObjSetStyleMarginBottom', obj, value, selector)
%     PsychLVGL('ObjSetStyleMarginHor', obj, value, selector)
%     PsychLVGL('ObjSetStyleMarginLeft', obj, value, selector)
%     PsychLVGL('ObjSetStyleMarginRight', obj, value, selector)
%     PsychLVGL('ObjSetStyleMarginTop', obj, value, selector)
%     PsychLVGL('ObjSetStyleMarginVer', obj, value, selector)
%     PsychLVGL('ObjSetStyleMaxHeight', obj, value, selector)
%     PsychLVGL('ObjSetStyleMaxWidth', obj, value, selector)
%     PsychLVGL('ObjSetStyleMinHeight', obj, value, selector)
%     PsychLVGL('ObjSetStyleMinWidth', obj, value, selector)
%     PsychLVGL('ObjSetStyleOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleOpaLayered', obj, value, selector)
%     PsychLVGL('ObjSetStyleOutlineColor', obj, value, selector)
%     PsychLVGL('ObjSetStyleOutlineOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleOutlinePad', obj, value, selector)
%     PsychLVGL('ObjSetStyleOutlineWidth', obj, value, selector)
%     PsychLVGL('ObjSetStylePadAll', obj, value, selector)
%     PsychLVGL('ObjSetStylePadBottom', obj, value, selector)
%     PsychLVGL('ObjSetStylePadColumn', obj, value, selector)
%     PsychLVGL('ObjSetStylePadGap', obj, value, selector)
%     PsychLVGL('ObjSetStylePadHor', obj, value, selector)
%     PsychLVGL('ObjSetStylePadLeft', obj, value, selector)
%     PsychLVGL('ObjSetStylePadRadial', obj, value, selector)
%     PsychLVGL('ObjSetStylePadRight', obj, value, selector)
%     PsychLVGL('ObjSetStylePadRow', obj, value, selector)
%     PsychLVGL('ObjSetStylePadTop', obj, value, selector)
%     PsychLVGL('ObjSetStylePadVer', obj, value, selector)
%     PsychLVGL('ObjSetStyleRadialOffset', obj, value, selector)
%     PsychLVGL('ObjSetStyleRadius', obj, value, selector)
%     PsychLVGL('ObjSetStyleRecolor', obj, value, selector)
%     PsychLVGL('ObjSetStyleRecolorOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleRotarySensitivity', obj, value, selector)
%     PsychLVGL('ObjSetStyleShadowColor', obj, value, selector)
%     PsychLVGL('ObjSetStyleShadowOffsetX', obj, value, selector)
%     PsychLVGL('ObjSetStyleShadowOffsetY', obj, value, selector)
%     PsychLVGL('ObjSetStyleShadowOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleShadowSpread', obj, value, selector)
%     PsychLVGL('ObjSetStyleShadowWidth', obj, value, selector)
%     PsychLVGL('ObjSetStyleSize', obj, width, height, selector)
%     PsychLVGL('ObjSetStyleTextAlign', obj, value, selector)
%     PsychLVGL('ObjSetStyleTextColor', obj, value, selector)
%     PsychLVGL('ObjSetStyleTextDecor', obj, value, selector)
%     PsychLVGL('ObjSetStyleTextFont', obj, value, selector)
%     PsychLVGL('ObjSetStyleTextLeadingTrim', obj, value, selector)
%     PsychLVGL('ObjSetStyleTextLetterSpace', obj, value, selector)
%     PsychLVGL('ObjSetStyleTextLineSpace', obj, value, selector)
%     PsychLVGL('ObjSetStyleTextOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleTextOutlineStrokeColor', obj, value, selector)
%     PsychLVGL('ObjSetStyleTextOutlineStrokeOpa', obj, value, selector)
%     PsychLVGL('ObjSetStyleTextOutlineStrokeWidth', obj, value, selector)
%     PsychLVGL('ObjSetStyleTransformHeight', obj, value, selector)
%     PsychLVGL('ObjSetStyleTransformPivotX', obj, value, selector)
%     PsychLVGL('ObjSetStyleTransformPivotY', obj, value, selector)
%     PsychLVGL('ObjSetStyleTransformRotation', obj, value, selector)
%     PsychLVGL('ObjSetStyleTransformScale', obj, value, selector)
%     PsychLVGL('ObjSetStyleTransformScaleX', obj, value, selector)
%     PsychLVGL('ObjSetStyleTransformScaleY', obj, value, selector)
%     PsychLVGL('ObjSetStyleTransformSkewX', obj, value, selector)
%     PsychLVGL('ObjSetStyleTransformSkewY', obj, value, selector)
%     PsychLVGL('ObjSetStyleTransformWidth', obj, value, selector)
%     PsychLVGL('ObjSetStyleTranslateRadial', obj, value, selector)
%     PsychLVGL('ObjSetStyleTranslateX', obj, value, selector)
%     PsychLVGL('ObjSetStyleTranslateY', obj, value, selector)
%     PsychLVGL('ObjSetStyleWidth', obj, value, selector)
%     PsychLVGL('ObjSetStyleX', obj, value, selector)
%     PsychLVGL('ObjSetStyleY', obj, value, selector)
%     PsychLVGL('ObjSetWidth', obj, w)
%     PsychLVGL('ObjSetX', obj, x)
%     PsychLVGL('ObjSetY', obj, y)
%     ret = PsychLVGL('RollerCreate', parent)
%     ret = PsychLVGL('RollerGetSelected', obj)
%     buf = PsychLVGL('RollerGetSelectedStr', obj)
%     PsychLVGL('RollerSetOptions', obj, options, mode)
%     PsychLVGL('RollerSetSelected', obj, sel_opt, anim)
%     PsychLVGL('RollerSetVisibleRowCount', obj, row_cnt)
%     ret = PsychLVGL('SliderCreate', parent)
%     ret = PsychLVGL('SliderGetLeftValue', obj)
%     ret = PsychLVGL('SliderGetMaxValue', obj)
%     ret = PsychLVGL('SliderGetMinValue', obj)
%     ret = PsychLVGL('SliderGetMode', slider)
%     ret = PsychLVGL('SliderGetValue', obj)
%     PsychLVGL('SliderSetMode', obj, mode)
%     PsychLVGL('SliderSetOrientation', obj, orientation)
%     PsychLVGL('SliderSetRange', obj, min, max)
%     PsychLVGL('SliderSetStartValue', obj, value, anim)
%     PsychLVGL('SliderSetValue', obj, value, anim)
%     ret = PsychLVGL('SpinboxCreate', parent)
%     PsychLVGL('SpinboxDecrement', obj)
%     ret = PsychLVGL('SpinboxGetValue', obj)
%     PsychLVGL('SpinboxIncrement', obj)
%     PsychLVGL('SpinboxSetDigitFormat', obj, digit_count, sep_pos)
%     PsychLVGL('SpinboxSetRange', obj, min_value, max_value)
%     PsychLVGL('SpinboxSetStep', obj, step)
%     PsychLVGL('SpinboxSetValue', obj, v)
%     ret = PsychLVGL('SwitchCreate', parent)
%     ret = PsychLVGL('TableCreate', parent)
%     ret = PsychLVGL('TableGetCellValue', obj, row, col)
%     [row, col] = PsychLVGL('TableGetSelectedCell', obj)
%     PsychLVGL('TableSetCellValue', obj, row, col, txt)
%     PsychLVGL('TableSetColumnCount', obj, col_cnt)
%     PsychLVGL('TableSetColumnWidth', obj, col_id, w)
%     PsychLVGL('TableSetRowCount', obj, row_cnt)
%     PsychLVGL('TextareaAddChar', obj, c)
%     PsychLVGL('TextareaAddText', obj, txt)
%     ret = PsychLVGL('TextareaCreate', parent)
%     PsychLVGL('TextareaDeleteChar', obj)
%     ret = PsychLVGL('TextareaGetCursorPos', obj)
%     ret = PsychLVGL('TextareaGetText', obj)
%     PsychLVGL('TextareaSetAcceptedChars', obj, list)
%     PsychLVGL('TextareaSetCursorPos', obj, pos)
%     PsychLVGL('TextareaSetMaxLength', obj, num)
%     PsychLVGL('TextareaSetOneLine', obj, en)
%     PsychLVGL('TextareaSetPasswordMode', obj, en)
%     PsychLVGL('TextareaSetPlaceholderText', obj, txt)
%     PsychLVGL('TextareaSetText', obj, txt)
%
%   StyleSetProp takes the property names of the ObjSetStyle<Prop>
%   subcommands, for example 'bg_color' or 'text_font', and the same value.
%   Font arguments take a built-in name from FontList or a FontLoad handle.
%
%   See SPEC.md for the marshaling rules and README.md for the build.

error('psychlvgl:NotBuilt', ...
      'The PsychLVGL MEX is not built. Run build, then PsychLVGLSetup.');
end
